name: rutinas codependientes
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo "paso 1"
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: echo "paso 2"
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "paso 3"
